[package]
name = "rust_csma_cd"
version = "0.1.0"
authors = ["mtalhauyar m.talhauyar@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
delay = "0.3.1"